server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9999/realms/memory

## Discover Server Route
  cloud:
    gateway:
      routes:
      - id: discovery-server
        uri: lb://{app.eureka-server}
        predicates:
        - Path=/eureka/web
        filters: SetPath=/

      - id: rewrite
        uri: lb://{app.eureka-server}
        predicates:
          - Path=/lastn
        filters:
          - RewritePath=/lastn(?<remaining>.*), /eureka/web/lastn$\{remaining}
          #- (?<segment>/?*), $\{segment}


      - id: rewrites
        uri: lb://{app.eureka-server}
        predicates:
          - Path=/eureka/web/lastn
        filters: SetPath=/lastn


  
      ## Discover Server Static Resources Route
      - id: discovery-server-static
        uri: lb://{app.eureka-server}
        predicates:
        - Path=/eureka/**

      ## IAM-SERVICE Route
      - id: iam-server-docs
        uri: lb://iam-service
        predicates:
          - Path=/iam-service/v3/api-docs
        ## IAM-SERVICE Route

      - id: iam-server-docs
        uri: lb://iam-service
        predicates:
          - Path=/iam-service/v3/api-docs
        #filters:
        #  - SetPath=/v3/docs

      ##
      - id: iam-server
        uri: lb://iam-service
        predicates:
          - Path=/api/iam-service/**
        filters:
         - RewritePath=/api/iam-service/(?<remaining>.*), /api/iam-service/$\{remaining}

    discovery:
      enabled: true
### Spring docs OpenIA
#springdoc:
#  swagger-ui:
#   path=/swagger-ui.html
springdoc:
  enableNativeSupport: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /iam-service/v3/api-docs
        name: IAM Service
        primaryName: iam-service

openapi:
  service:
    title: API-GATEWAY #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:${server.port} #api gateway url



app:
  eureka-server: discovery-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE