server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:9999/realms/memory
  
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0


## Discover Server Route
  cloud:
    gateway:
      routes:
      - id: discovery-server
        uri: http://eureka:eureka@${app.eureka-server}:8761
        predicates:
        - Path=/eureka/web
        filters: SetPath=/

      - id: rewrite
        uri: http://${spring.application.name}:8080
        predicates:
          - Path=/lastn
        filters:
          - RewritePath=/lastn(?<remaining>.*), /eureka/web/lastn$\{remaining}
          #- (?<segment>/?*), $\{segment}


      - id: rewrites
        uri: http://eureka:eureka@${app.eureka-server}:8761
        predicates:
          - Path=/eureka/web/lastn
        filters: SetPath=/lastn

      ## Discover Server Static Resources Route
      - id: discovery-server-static
        uri: http://eureka:eureka@${app.eureka-server}:8761
        predicates:
        - Path=/eureka/**

      ## IAM-SERVICE Route
      - id: iam-server-docs
        uri: ${iam.uri}
        predicates:
          - Path=/iam-service/v3/api-docs
        ## IAM-SERVICE Route

      - id: iam-server-docs
        uri: ${iam.uri}
        predicates:
          - Path=/iam-service/v3/api-docs
        #filters:
        #  - SetPath=/v3/docs
      ##
      - id: iam-server
        uri: ${iam.uri}
        predicates:
          - Path=/api/iam-service/**
        filters:
         - RewritePath=/api/iam-service/(?<remaining>.*), /api/iam-service/$\{remaining}

    discovery:
      enabled: true

### Spring docs OpenIA
#springdoc:
#  swagger-ui:
#   path=/swagger-ui.html
springdoc:
  enableNativeSupport: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /iam-service/v3/api-docs
        name: IAM Service
        primaryName: iam-service

openapi:
  service:
    title: ${spring.application.name} #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:${server.port} #api gateway url


iam:
  uri: http://iam-service:8081

app:
  eureka-server: discovery-server-0.eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    serviceUrl:
      defaultZone: http://eureka:eureka@${app.eureka-server}:8761/eureka
#    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE




test: "Hello 1"

