server:
  port: 8761


spring:
  application:
    name: discovery-server
#  cloud:
#    config:
#      import-check:
#        enabled=false


zipkin:
  base-url: ${ZIPKIN_URI:http://zipkin:9411}
sleuth:
  sampler:
    probability: 1.0

app:
  eureka:
    username: eureka
    password: eureka

eureka:
  instance:
    #preferIpAddress: true
    hostname: "${spring.application.name}"
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl:
      #defaultZone: ${EUREKA_SERVER_ADDRESS}
    #  defaultZone: http://eureka:eureka@${eureka.instance.hostname}:${server.port}/eureka/
  #server:
  #  enable-self-preservation: false

  username: ${EUREKA_USERNAME:${app.eureka.username}}
  password: ${EUREKA_PASSWORD:${app.eureka.password}}


management:
  endpoints:
    web:
      exposure:
        include: "*"