server:
  port: 8761


spring:
  application:
    name: discovery-server
#  cloud:
#    config:
#      import-check:
#        enabled=false

app:
  eureka:
    username: eureka
    password: eureka

eureka:
  instance:
    hostname: "${spring.application.name}.eureka"
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serverUrl: ${EUREKA_SERVER_ADDRESS}
    serverUrl:  
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # username: ${EUREKA_USERNAME:eureka}
  # username: eureka
  
  # password: ${EUREKA_PASSWORD:eureka}
  # password: eureka
