server:
  port: 8761

spring:
  application:
    name: discovery-server

zipkin:
  base-url: ${ZIPKIN_URI:http://zipkin:9411} 
sleuth:
  sampler:
    probability: 1.0

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serverUrl: http://localhost:${server.port}/eureka/
    # Autre configuration du client Eureka

  instance:
    hostname: "${spring.application.name}.eureka"

app:
  eureka:
    username: eureka
    password: eureka



management:
  endpoints:
    web:
      exposure:
        include: "*"